export default {
  "新增": "primary",
  "新增/变更": "primary",
  "新增/重检": "primary",
  "添加": "primary",
  "新增缴费记录": "primary",
  "查询": "primary",
  "查询账户余额": "primary", 
  "同意": "primary",
  "确定": "primary",
  "复制新增": "primary",
  "复制": "primary",
  "产品适用机构配置":"primary",
  "专案适用机构配置": "primary",
  "选择出账策略": "primary",
  "选择定价策略": "primary",
  "选择还款方式策略": "primary",
  "选择影像包": "primary",
  "关联岗位设置": "primary",
  "名单新增":"primary",
  "提起审批":"primary",
  "收回":"primary",
  "确定并关闭":"primary",
  "选取返回":"primary",
  "初分认定":"primary",
  "通知核算记账":"primary",
  "维护":"primary",
  "回款账户及授信审批通知":"primary", 
  "通知核算还款":"primary",
  "下一步":"primary",
  "选中并关联":"primary",
  "试算新还款计划":"primary",
  "试算":"primary",
  "启用":"primary",
  "刷新轨迹": "primary",
  "获得机评得分": "primary",
  "添加保证人": "primary",
  "引入抵押品": "primary",
  "引入质押品": "primary",
  "引入": "primary",
  "担保人催收函": "primary",
  "重查": "primary",
  "保存": "primary",
  "新增-保存": "primary",
  "修改-保存": "primary",
  "计算": "primary",
  "添加单项": "primary",
  "添加组合": "primary",
  "单任务激活": "primary",
  "批量任务激活": "primary",
  "通知类单任务激活": "primary",
  "通知类批量任务激活": "primary",
  "签订协议": "primary",
  "生成新版本": "primary",
  "暂存": "primary",
  "获取": "primary",
  "测算": "primary",
  "开始会议": "primary",
  "重新开始会议": "primary",
  "修改数据": "primary",
  "切换模式": "primary",
  "分配机构": "primary",
  "分配经理": "primary",
  "通知平台": "primary",
  "返回添加": "primary",
  "选择业务交易编号": "primary",
  "调账": "primary",
  "核算冲正": "primary",
  "还款测算": "primary",
  "退回补充资料": "danger",
  "退回注明要求": "danger",
  "确定转办": "primary",
  "确定协办": "primary",
  "开始仿真": "primary",
  "仿真进行中": "primary",
  "刷新": "primary",
  "欠款查询": "primary",
  "还款计划查询": "primary",
  "还款记录查询": "primary",
  "上一步":"primary",
  "赋值":"primary",
  "提交":"primary",
  "全部提交":"primary",
  "发起流程":"primary",
  "发起流程并提交":"primary",
  "重新发起":"primary",
  "验证并保存":"primary",
  "日历":"primary",
  "放款通知":"primary",
  "应收账款债权转让通知":"primary",
  "生效":"primary",
  "搜索":"primary",
  "统计":"primary",
  "估一估":"primary",
  "估值申请":"primary",
  //
  "重置": "info",
  "查看": "info",
  "取消": "info",
  "返回": "info",
  "产品/专案使用记录": "info",
  "产品使用记录": "info",
  "预览": "info",
  "下载": "info",
  "查询结果下载": "info",
  "宣传详情": "info",
  "导出": "info",
  "对比": "info",
  "设计": "info",
  "流程轨迹": "info",
  "打印凭证":"info",
  "还款撤销凭证":"info",
  "打印":"info",
  "导出EXCEL":"info",   
  "导入EXCEL":"info",  
  "批量导入":"info",
  "导入":"info",
  "下载模板":"info",
  "调阅/下载":"info",
  "获取验证码":"info",
  "导出Csv(推荐)":"info",
  "审批详情":"info",
  "主动还款凭证":"info",
  "导出事前审批单":"info",
  "返回到列表界面":"info", 
  "查看现还款计划信息":"info",
  "回执":"info",
  "借款人催收函":"info",
  "综合信息":"info",
  "缴费记账": "info",
  "信息同步": "info",
  "收取/撤销凭证打印":"info",
  "影像查看": "info",
  "详情": "info",
  "查看协议":"info",
  "重置流水号":"info",
  "划款打印":"info",
  "生成js":"info",
  "预览模型":"info",
  "模板下载":"info",
  "获取核心客户号":"info",
  //
  "修改": "warning",
  "修改敞口额度": "warning",
  "减值准备金额修改": "warning",
  "检查": "warning",
  "年审":"warning",
  "重新赔付":"warning",
  "排查":"warning",
  "处置":"warning",
  "签订":"warning",
  "签章":"warning",
  "额度占用":"warning",
  "授权通知":"warning",
  "发起保证金划转":"warning",
  "发起保证金支取":"warning",
  "发起审批": "warning",
  "特批准入":"warning",
  "撤销": "warning",
  "收取撤销": "warning",
  "手续费划转": "warning",
  "校验":"warning",
  "上传/更改":"warning",
  "发布":"warning",
  "发起调查":"warning",
  "重新调查":"warning",
  "补录":"warning",
  "重新估值":"warning",
  "发放授权":"warning",
  "资金划转":"warning",
  //
  "废弃": "danger",
  "删除": "danger",
  "删除任务":"danger",
  "停用": "danger",
  "启用停用": "danger",
  "主动作废":"danger",
  "解除":"danger",
  "变更":"danger",
  "解除|变更-通知核心企业":"danger",
  "否决":"danger",
  "退回":"danger",
  "发起销户":"danger",
  "关闭": "danger", 
  "解散协议":"danger",
  "全部删除":"danger",
  "移除":"danger",
  "资金监管协议撤销":"danger",

}